### ISSUE TITLE
Create account function fails on testnet.

### ISSUE THREAD

**Issue by PierreLeGuen** [near/near-api-js#1041]
**Describe the bug**

On tesnet the createAccount method fails.

**To Reproduce**
1. Communicate with testnet RPC
2. Code to replicate the error:

```
  const near = await connect({ ...config, keyStore });
  const creatorAccount = await near.account(creatorAccountId);
  await creatorAccount.createAccount(newAccountId, publicKey, "10000000000000000000");
```

**Expected behavior**
```
ServerTransactionError: The new account_id test-account-bis.testnet can't be created by garbage-account.testnet
    at parseResultError (/Users/pierreleguen/WebstormProjects/oracle-test/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.<anonymous> (/Users/pierreleguen/WebstormProjects/oracle-test/node_modules/near-api-js/lib/account.js:156:61)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/pierreleguen/WebstormProjects/oracle-test/node_modules/near-api-js/lib/account.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'CreateAccountNotAllowed',
  context: undefined,
  index: 0,
  account_id: 'test-account-bis.testnet',
  predecessor_id: 'garbage-account.testnet',
  kind: {
    account_id: 'test-account-bis.testnet',
    predecessor_id: 'garbage-account.testnet'
  },
  transaction_outcome: {
    block_hash: '3B7mxHpcS8Q8fifdYRoXihTCKM8xfUb3mVEWiXxi18pb',
    id: '6ChTNgqdija2kgopEU2d2zMJCPKPJ6AvLsmM8KjqNHvK',
    outcome: {
      executor_id: 'garbage-account.testnet',
      gas_burnt: 424555062500,
      logs: [],
      metadata: { gas_profile: null, version: 1 },
      receipt_ids: [ 'ssXAwmZfuU2ArukWyhFkwpGNJyWHBHsKGitZze4svb4' ],
      status: {
        SuccessReceiptId: 'ssXAwmZfuU2ArukWyhFkwpGNJyWHBHsKGitZze4svb4'
      },
      tokens_burnt: '42455506250000000000'
    },
    proof: [
      {
        direction: 'Right',
        hash: 'EDdn5i9Ym2CMxdtFSat42S6M4nDBsWvukFNDZV7hipnR'
      },
      {
        direction: 'Right',
        hash: 'E5mYgjPzNbWMCYf8CBTSvhtMkaihMguTd1dnA6Yzxtkt'
      }
    ]
  }
}

```

**Comment by andy-haynes** [comment]
@PierreLeGuen the `Account.createAccount()` method can actually only create sub-accounts on the represented account, i.e. `xyz.garbage-account.testnet`. For an example of creating a new account on `testnet` see the cookbook entry here: https://github.com/near/near-api-js/blob/master/packages/cookbook/accounts/create-testnet-account.js#L34
```
  await creatorAccount.functionCall({
    contractId: "testnet",
    methodName: "create_account",
    args: {
      new_account_id: newAccountId,
      new_public_key: publicKey,
    },
    gas: "300000000000000",
    attachedDeposit: utils.format.parseNearAmount(amount),
  });
```

This is confusing to say the least. The `Account` method should be named clearly to indicate that it creates sub-accounts, and the responsibility of creating new accounts should be more obvious IMO.
