### ISSUE TITLE
Help for requestSignTransactions

### ISSUE THREAD

**Issue by ghost** [near/near-api-js#1050]
How do I call the `requestSignTransactions`?

I am trying to call the `nft_mint` action on a contract. Here is the code I am trying but it is not working.

```ts
  const response = await walletConnection.requestSignTransactions({
    callbackUrl: `http://localhost:3000/callback`,
    transactions: [
      new nearAPI.transactions.Transaction({
        receiverId: my_contract_address,
        actions: [
          {
            functionCall: {
              args: new TextEncoder().encode(
                JSON.stringify({ collection_id: 123 }),
              ),
              deposit: new BN(parseNearAmount('15') || 0),
              gas: new BN(100000000000000),
              methodName: 'nft_mint',
            },
          },
        ],
      }),
    ],
  });
```

Any help would be appreciated

**Comment by sulaysumaria** [comment]
Getting following error now:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'borshSerialize')
    at serializeStruct (index.js:317:1)
    at serializeField (index.js:306:1)
    at index.js:327:1
    at Array.map (<anonymous>)
    at serializeStruct (index.js:326:1)
    at serialize (index.js:349:1)
    at wallet-account.js:168:1
    at Array.map (<anonymous>)
    at WalletConnection.<anonymous> (wallet-account.js:168:1)
    at Generator.next (<anonymous>)
    at wallet-account.js:8:1
    at new Promise (<anonymous>)
    at push../node_modules/near-api-js/lib/wallet-account.js.__awaiter (wallet-account.js:4:1)
    at WalletConnection.requestSignTransactions (wallet-account.js:165:1
)
```

<img width="778" alt="Screenshot 2022-12-26 at 1 18 59 PM" src="https://user-images.githubusercontent.com/20580362/209520523-b2a02015-5c83-4635-a48b-2d79c526ad26.png">

**Comment by sulaysumaria** [comment]
Turns out the issue from our end itself.

Once user is redirected to out platform after clicking on "connect", we need to immediately connect the wallet. I think the `near-api-js` needs the query params returned by the wallet to make a connection.

This needs to be documented somewhere.

**Comment by gagdiez** [comment]
now frontend is handled through `wallet-selector`
