### ISSUE TITLE
Error: Length of buffer does not match length of ASN.1 sequence

### ISSUE THREAD

**Issue by microchipgnu** [near/near-api-js#1248]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [x] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [x] I have read the console error messages carefully (if applicable).

### Description

We have several users using Chromium-based browsers (v120+) like Brave, Chrome and Edge on Windows machines.

We integrated `@near-js/biometric-ed25519` and the `getKeys` method throws an error when executed in this environment.

### Reproducible demo

https://wallet.mintbase.xyz

### Steps to reproduce

1. Open any browser based on Chromium (v120+) on a Windows machine
2. Create an account (this should work)
3. [Try signing any transaction with the wallet](https://wallet.mintbase.xyz/s/ERjPpoE-NThJM40XiMURQ/)

### Expected behavior

Not to throw an error and return keys.

### Actual behavior

```
Error: Length of buffer does not match length of ASN.1 sequence.
at V.parse (4011-d66488a438fc0322.js:477:36669)
at 4011-d66488a438fc0322.js:470:51173
at Generator.next (<anonymous>)
at 4011-d66488a438fc0322.js:470:49049
at new Promise (<anonymous>)
at en (4011-d66488a438fc0322.js:470:48830)
at 4011-d66488a438fc0322.js:470:50853
at async i (page-4ae5a0be2a9f3743.js:1:20136)
at async sendTransaction (page-4ae5a0be2a9f3743.js:1:15438)
at async send (page-4ae5a0be2a9f3743.js:1:16668) 'error'
```

### Your environment

- NEAR JavaScript API version used: 1.0.1
- Frontend framework (if applicable): NextJS (client rendered component)
- OS: Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by gtsonevv** [comment]
Hey @microchipgnu, we have updated the package, the problem should be solved.

**Comment by microchipgnu** [comment]
Thanks @gtsonevv we are testing now.

**Comment by microchipgnu** [comment]
Hey @gtsonevv we are seeing a new error now

```
Error: r must be 0 < r < CURVE.n 
    at eO.assertValidity (6887-25fc58e43eeff16f.js:471:77431)
    at new eO (6887-25fc58e43eeff16f.js:471:77159)
    at 6887-25fc58e43eeff16f.js:470:54149
    at Generator.next (<anonymous>)
    at 6887-25fc58e43eeff16f.js:470:52568
    at new Promise (<anonymous>)
    at en (6887-25fc58e43eeff16f.js:470:52349)
    at em (6887-25fc58e43eeff16f.js:470:54012)
    at 6887-25fc58e43eeff16f.js:470:51450
    at Generator.next (<anonymous>) 'error'
    ```

**Comment by gtsonevv** [comment]
Hey @microchipgnu, we will investigate why this is happening.

**Comment by gtsonevv** [comment]
@microchipgnu, is this error coming from the `getKeys` method again?

**Comment by vikinatora** [comment]
Hey @microchipgnu, could you provide a minimal reproducible example of the issue?

**Comment by microchipgnu** [comment]
Any update @vikinatora @gtsonevv?

**Comment by gtsonevv** [comment]
Hey @microchipgnu, we are still investigation the issue, please use version 2.1.4 until we resolve the issue.

**Comment by vikinatora** [comment]
@SurgeCode, @microchipgnu Does the issues still persist on near-api-js v2.1.4? This issue is on our priority list, but we have a few other stuff to do, before we dive deep here. Thank you for your patience.

**Comment by SurgeCode** [comment]
1.0.1 -> Doesn't work on any window machines - Error: Length of buffer does not match length of ASN.1 sequence.

1.1.0 -> Doesn't work in general (all machines we tested)- Error: r must be 0 < r < CURVE.n 

reproduction -> create, get, check console https://near-biometric-issue-repro.vercel.app/

This issue is quite critical for us at the moment

**Comment by vikinatora** [comment]
Hey, no update here unfortunately. Most likely the `asn-parser` library is causing the issue. Replacing it would require refactoring of the existing functionality, so I can't give you an estimate of when you can expect this issue to be resolved.

**Comment by SurgeCode** [comment]
This seems pretty critical as it makes the library entirely unusable in a lot of cases. Could you give me some information on how much of a priority this is for your team or if we should explore our own implementation?

**Comment by vikinatora** [comment]
It's high priority. @gtsonevv is on it.

**Comment by vikinatora** [comment]
Hey, we’ve been investigating the issue in the past weeks. Unfortunately, no substantial progress has been made and this issue won't be a quick fix. We're researching currently what it will take to make the module working.

For the time being, please use v1.0.1 which doesn't work on Windows as per your comments.

**Comment by vikinatora** [comment]
#1309 Should resolve the issue, waiting for the CI node to be back up, so that checks can pass and we will release it. 
Thank you for the patience.

**Comment by microchipgnu** [comment]
We will give this a try. Thanks!

**Comment by vikinatora** [comment]
Please let us know if the issue is resolved. Package is [@near-js/biometric-ed25519@1.1.2](https://github.com/near/near-api-js/releases/tag/%40near-js%2Fbiometric-ed25519%401.1.2)

**Comment by starpause** [comment]
https://github.com/near/near-api-js/assets/408953/c000af87-37a9-4fe0-a541-cbcd38bb2cbd

**Comment by vikpande** [comment]
@vikinatora , do you want to jam on this one over a call & close this? its been a while and Mintbase is getting a lot of not-so-happy users coz of it.

**Comment by SurgeCode** [comment]
I'm also happy to contribute to get this fixed

**Comment by vikinatora** [comment]
Contributions are more than welcome, our tem has comittment on a different group of functionalities and we're trying to solve this issue with the time we have to spare between tasks.

Unfortunately, the issue here is not an easy one.

**Comment by vikinatora** [comment]
My thoughts are to resolve the windows issue, the whole fido2-lib will have to be replaced with an alternative. 

Regarding the signing issue, that's probably a hard to spot bug. We've not worked on the initial implementation and it's hard to debug as there are no tests for the biometric module.

**Comment by vikinatora** [comment]
@starpause, @myweb3gift can you try out the logic [here](https://naj-issue-next.vercel.app/)? I've replaced the ASN.1 parsing library, maybe that will help as I couldn't reproduce the issue on my windows machine.

In the app you just have to press the "Create and Get Key" button and check the console for errors.

**Comment by starpause** [comment]
@vikinatora we had been chatting on telegram but thought to update the issue with my findings after you replaced the ASN.1 library.

I still get an error in console: `Error initializing NEAR: Length over 48 bits not supported at position 1`

https://github.com/near/near-api-js/assets/408953/9578fbf4-6dca-4fdd-b218-18691be1db08

**Comment by ssplashh** [comment]
Hi, I try to log in the account with the Windows passkey, when I type the PIN it doesn't tell me it's incorrect, but it won't loge me in.  Also, I have another account I'm logged on, but it's impossible to get the seed phrase. I'm using Windows 10 and latest version of Chrome. After I put the PIN, I'm back to the connection page, nothing happens. Please, advise.

![image](https://github.com/near/near-api-js/assets/128165996/14104124-13ad-429d-ad5f-92d044c49e82)
![image](https://github.com/near/near-api-js/assets/128165996/e0ec9818-40e9-42d2-a19c-6421608e756e)

**Comment by starpause** [comment]
@vikinatora After bumping Mintbase Wallet dependency to @near-js/wallet-account@1.2.1 I'm still getting the ASN.1 error on my windows machine. Can you share a barebones test before pushing the next fix/update to make the feedback loop tighter? This has been open for months. Maybe fork https://near-biometric-issue-repro.vercel.app/ as shared above?
