### ISSUE TITLE
Local Node: Socket hung up (RPC) 

### ISSUE THREAD

**Issue by k9thebeast** [near/near-api-js#229]
Happens randomly, intermittently, cannot duplicate successfully (yet) 

Would be nice to have some sort of `retries` parameter / config as well

```
 1|api-beta | 2020-02-14T22:55:45.155Z <span class="error">[error]</span>: No global handler was attached and a generic error was thrown:
 1|api-beta | FetchError: request to [http://localhost:3030/](http://localhost:3030/) failed, reason: socket hang up
 1|api-beta | at ClientRequest.<anonymous> (/root/stardust2/backend/node_modules/node-fetch/lib/index.js:1455:11)
 1|api-beta | at ClientRequest.emit (events.js:198:13)
 1|api-beta | at Socket.socketOnEnd (_http_client.js:426:9)
 1|api-beta | at Socket.emit (events.js:203:15)
 1|api-beta | at endReadableNT (_stream_readable.js:1145:12)
 1|api-beta | at process._tickCallback (internal/process/next_tick.js:63:19)
 1|api-beta | npm
 1|api-beta |
 ```

**Comment by nearmax** [comment]
I observed the same.

**Comment by bowenwang1996** [comment]
This also happens on CI from time to time.
