### ISSUE TITLE
Not enough balance error does not get formatted properly 

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-api-js#363]
To repro, from near shell run a near send which exceeds the balance of the sender account. 

The observed output is:
Sending 100000000 NEAR to jane3 from jane3.testnet
Error:  NotEnoughBalance [Error]: Sender jane3.testnet does not have enough balance {} for operation costing {}
    at Object.parseRpcError (C:\Users\janed\near\near-shell\node_modules\near-api-js\lib\utils\rpc_errors.js:38:19)
    at JsonRpcProvider.sendJsonRpc (C:\Users\janed\near\near-shell\node_modules\near-api-js\lib\providers\json-rpc-provider.js:146:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Account.signAndSendTransaction (C:\Users\janed\near\near-shell\node_modules\near-api-js\lib\account.js:115:22)
    at async exports.sendMoney (C:\Users\janed\near\near-shell\index.js:209:20)
    at async Object.handler (C:\Users\janed\near\near-shell\utils\exit-on-error.js:37:9) {
  type: 'NotEnoughBalance',
  balance: '499000000905435533954930000',
  cost: '100000000000000002265303009375000',
  signer_id: 'jane3.testnet'
}

Desired output is that the "Sender jane3.testnet does not have enough balance {} for operation costing {}" piece is properly formatted.

**Comment by chadoh** [comment]
Closed via #364
