### ISSUE TITLE
Better error message for bad receiver id

### ISSUE THREAD

**Issue by willemneal** [near/near-api-js#654]
Currently if an account id is invalid you get the following:

 {"kind":{"receiver_id":"AVL.test.near"}}
 at Object.parseRpcError (../../sandbox/npm/node_modules/near-api-js/lib/utils/rpc_errors.js:24:19)
 at ../../sandbox/npm/node_modules/near-api-js/lib/providers/json-rpc-provider.js:312:44
 at Object.exponentialBackoff <span class="error"><span class="error">[as default]</span></span> (../../sandbox/npm/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
 at JsonRpcProvider.sendJsonRpc (../../sandbox/npm/node_modules/near-api-js/lib/providers/json-rpc-provider.js:297:26)
 at ../../sandbox/npm/node_modules/near-api-js/lib/account.js:114:24
 at Object.exponentialBackoff <span class="error"><span class="error">[as default]</span></span> (../../sandbox/npm/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
 at Account.signAndSendTransactionV2 (../../sandbox/npm/node_modules/near-api-js/lib/account.js:110:24)
 at Account.createAndDeployContract (../../sandbox/npm/node_modules/near-api-js/lib/account.js:208:9)
 at SandboxRuntime.createAndDeploy (../../sandbox/npm/runner/src/index.ts:83:7)

It is unclear that `receiver_id` means invalid account/receiver id.

**Comment by hcho112** [comment]
team checked few scenarios that wasn't able to reproduce this error. Feel free to open this issue if you ever come across same error
