### ISSUE TITLE
Setting up fetch and declaring it as a global variable throws an error

### ISSUE THREAD

**Issue by Hatzz** [near/near-api-js#787]
***Describe the bug***
 When importing the near api modules the following error gets thrown:
 ```
 Cannot assign to read only property 'fetch' of object '#<Object>'
 TypeError: Cannot assign to read only property 'fetch' of object '#<Object>'
 at Object.<anonymous> (/Users/hatzz/code/inkawu-frontend/node_modules/near-api-js/lib/connect.js:35:14)
 at Module._compile (internal/modules/cjs/loader.js:1072:14)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
 at Module.load (internal/modules/cjs/loader.js:937:32)
 at Function.Module._load (internal/modules/cjs/loader.js:778:12)
 at Module.require (internal/modules/cjs/loader.js:961:19)
 at require (internal/modules/cjs/helpers.js:92:18)
 at Object.<anonymous> (/Users/hatzz/code/inkawu-frontend/node_modules/near-api-js/lib/index.js:28:14)
 at Module._compile (internal/modules/cjs/loader.js:1072:14)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
 ```
 Which goes to the following line in this library:
 [https://github.com/near/near-api-js/blob/0139380c986c88a6ea4a07d6ecb24194859fcc46/src/connect.ts#L30](https://github.com/near/near-api-js/blob/0139380c986c88a6ea4a07d6ecb24194859fcc46/src/connect.ts#L30)

I could fix it by simply deleting the line in my node_modules folder and still use the library since fetch is a global object in the frontend. I do believe however that the correct thing to do here is either to import fetch from `node-fetch` wherever it is used or add an if check when setting the global variable like this (tried and seemed to work):

```js
 if (!global.fetch) 

 { global.fetch = fetch; } 

```

***To Reproduce***
 1\. Create a new sveltekit project `npm init svelte@next`
 2\. `npm i near-api-js --save-dev`
 3\. Import near-api-js in `src/routes/index.svelte`
 4\. See error

**Comment by koen-vr** [comment]
Ran into the same issue: 
> The SDK tries to write to a global variable that on modern systems is supposed to be read-only. Long-term someone needs to go into the SDK and update the package to use a local variable for fetch where needed.

Ref. https://github.com/vecno-io/arc-near-client
