### ISSUE TITLE
near-api-js document does not reflect new version

### ISSUE THREAD

**Issue by Talented-Developer** [near/near-api-js#812]
config for near connect requires headers field in it, but could not find it on the document.
 #[https://docs.near.org/docs/api/naj-quick-reference](https://docs.near.org/docs/api/naj-quick-reference)

And they say keyStore is optional, but there happens this error when just to fetch account data.

```
 (node:9420) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'keyStore' of undefined
 at new Near (D:\Worksite\dvst\dvst-web3\node_modules\near-api-js\lib\near.js:34:105)
 at connect (D:\Worksite\dvst\dvst-web3\node_modules\near-api-js\lib\connect.js:65:12)
 at NearLogic.<anonymous> (D:\Worksite\dvst\dvst-web3\build\chains\near.js:204:58)
 at step (D:\Worksite\dvst\dvst-web3\build\chains\near.js:71:23)
 at Object.next (D:\Worksite\dvst\dvst-web3\build\chains\near.js:52:53)
 at D:\Worksite\dvst\dvst-web3\build\chains\near.js:46:71
 at new Promise (<anonymous>)
 at __awaiter (D:\Worksite\dvst\dvst-web3\build\chains\near.js:42:12)
 at D:\Worksite\dvst\dvst-web3\build\chains\near.js:186:87
 at new Promise (<anonymous>)
 at NearLogic.<anonymous> (D:\Worksite\dvst\dvst-web3\build\chains\near.js:186:39)
 at step (D:\Worksite\dvst\dvst-web3\build\chains\near.js:71:23)
 at Object.next (D:\Worksite\dvst\dvst-web3\build\chains\near.js:52:53)
 at D:\Worksite\dvst\dvst-web3\build\chains\near.js:46:71
 at new Promise (<anonymous>)
 at __awaiter (D:\Worksite\dvst\dvst-web3\build\chains\near.js:42:12)
 (Use `node --trace-warnings ...` to show where the warning was created)
 (node:9420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see [https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode](https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode)). (rejection id: 3)
 (node:9420) <span class="error">[DEP0018]</span> DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 ```

**Comment by dfl-grisha** [comment]
I have the same issue, thought specifying `keyStore` was not necessary if you aren't going to sign transactions.
Also any minimal working example on how to connect to NEAR network would be great.
