### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by KorayBarkin** [near/near-api-js#858]
I'm trying to write a simple node health check code but it keeps giving me an error related with window. In the documentation keyStore written as optional if not signing transaction but when I leave it empty it gives an error. Any help appreciated.
```
const nearAPI = require("near-api-js");

const { connect, WalletConnection, keyStores } = nearAPI;
const keyStore = new keyStores.BrowserLocalStorageKeyStore();
const config = {
  networkId: "mainnet",
  keyStore,
  nodeUrl: "https://rpc.mainnet.near.org",
  walletUrl: "https://wallet.mainnet.near.org",
  helperUrl: "https://helper.mainnet.near.org",
  explorerUrl: "https://explorer.mainnet.near.org",
};
const nearHealth = async () => {
  // connect to NEAR
  const near = await connect(config);
  const response = await near.connection.provider.status();
  // create wallet connection

  console.log(response);
};

nearHealth();

```

```
/Users/icrypexbilisim/nearservices/node_modules/near-api-js/lib/key_stores/browser_local_storage_key_store.js:34
    constructor(localStorage = window.localStorage, prefix = LOCAL_STORAGE_KEY_PREFIX) {
                               ^

ReferenceError: window is not defined
    at new BrowserLocalStorageKeyStore (/Users/icrypexbilisim/nearservices/node_modules/near-api-js/lib/key_stores/browser_local_storage_key_store.js:34:32)
    at Object.<anonymous> (/Users/icrypexbilisim/nearservices/index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by giraffekey** [comment]
Are you using SSR by chance? (Next, Nuxt, SvelteKit)

If so you can do something like this:

```js
const keyStore = isBrowser && new keyStores.BrowserLocalStorageKeyStore()
```

If you aren't using the browser at all I'm not sure why you're using the localStorage key store.
