### ISSUE TITLE
Module "fs" has been externalized for browser compatibility and cannot be accessed in client code.

### ISSUE THREAD

**Issue by masafumimori** [near/near-api-js#889]
**Describe the bug** Trying to use Vite and near-api-js and error below occurs.

```
 Uncaught Error: Module "fs" has been externalized for browser compatibility and cannot be accessed in client code.
 at Object.get (browser-external:fs:3:11)
 at node_modules/near-api-js/lib/key_stores/unencrypted_file_system_keystore.js (unencrypted_file_system_keystore.js:20:39)
 at __require2 (chunk-OROXOI2D.js?v=32b5dd11:16:50)
 at node_modules/near-api-js/lib/key_stores/index.js (index.js:11:44)
 at __require2 (chunk-OROXOI2D.js?v=32b5dd11:16:50)
 at node_modules/near-api-js/lib/index.js (index.js:26:34)
 at __require2 (chunk-OROXOI2D.js?v=32b5dd11:16:50)
 at dep:near-api-js_lib:1:16
```

**To Reproduce** Steps to reproduce the behavior:

1.  Go to '[my repo](https://github.com/masafumimori/dApps_samples)'
2.  Clone the project
3.  Move to `near-wasm` directory
4.  yarn install & yarn dev etc

**Expected behavior** No error occurs and display component

**Desktop (please complete the following information):**

*   OS: MacOS M1Pro
*   Version Monetary v12.0

**Comment by esaminu** [comment]
@masafumimori It's happening because you are importing directly via `near-api-js/lib`. You should change the import to just `near-api-js` since [the browser index is `lib/browser-index.js`](https://github.com/near/near-api-js/blob/master/package.json#L11) 🙂

**Comment by masafumimori** [comment]
@esaminu 
YES!!!
It all worked fine after removing `/lib` like you said. Thanks a lot!!
